# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('schedule', '0003_myspecialuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myspecialuser',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
