# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-24 17:16
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_myspecialuser_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='myspecialuser',
            name='color',
            field=colorful.fields.RGBColorField(default=('#FF0000')),
            preserve_default=False,
        ),
    ]
