# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockMarket', '0002_sharemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='author',
        ),
        migrations.AlterModelOptions(
            name='sharemodel',
            options={'ordering': ['name_ref']},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
